title: "IT KRIEBBELS"
description: "Freelance .NET Developer – Building secure, clear, and reliable solutions"
author: "Kristof Riebbels"
baseurl: "" # For project pages, use "/project-name"
url: "https://it.kriebbels.me"
github_username: kriebb

# Build settings
theme: minima
markdown: kramdown
highlighter: rouge

liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Disable parallel processing
parallel: false
# Jekyll SEO Tag
lang: en_US
locale: nl_BE
social:
  name: Kristof Riebbels
  links:
    - https://github.com/kriebb
    - https://www.linkedin.com/in/kristofriebbels

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-polyglot

# Sass processing
sass:
  sass_dir: _sass
  style: compressed

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - node_modules
  - .git
  - .github
  - vendor

# Default front matter for pages
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /blog/:title/


# Add these language settings to your existing _config.yml

# Language settings
languages: ["en", "nl"]
default_lang: "en"
exclude_from_localization: ["assets", "images", "css", "js", "fonts", "favicon.ico"]
parallel_localization: true
# Language names for UI
lang_names:
  en: English
  nl: Nederlands
  
# Translations directory
translations_dir: _data/i18n

# Additional language-specific settings
t:
  en:
    language: "English"
    icon: "🇬🇧"
    locale: en_US
  nl:
    language: "Nederlands"
    icon: "🇳🇱"
    locale: nl_NL

permalink: /:categories/:title/